// api.js - GIVEN. Do not edit this file.
// It pretends to be a slow, occasionally failing HTTP API.

const ORDERS = [
  { id: 1,  customer: "Cleo",    amount: 120.5, status: "paid" },
  { id: 2,  customer: "Ana",     amount: 80,    status: "pending" },
  { id: 3,  customer: "Bo",      amount: 240.25,status: "paid" },
  { id: 4,  customer: "Cleo",    amount: 15,    status: "cancelled" },
  { id: 5,  customer: "Dmitri",  amount: 310,   status: "paid" },
  { id: 6,  customer: "Ana",     amount: 45.75, status: "paid" },
  { id: 7,  customer: "Eve",     amount: 999,   status: "paid" },
  { id: 8,  customer: "Bo",      amount: 60,    status: "pending" },
  { id: 9,  customer: "Cleo",    amount: 200,   status: "paid" },
  { id: 10, customer: "Eve",     amount: 30.5,  status: "cancelled" },
  { id: 11, customer: "Dmitri",  amount: 75,    status: "paid" },
  { id: 12, customer: "Ana",     amount: 190,   status: "paid" },
  { id: 13, customer: "Bo",      amount: 500,   status: "paid" },
  { id: 14, customer: "Eve",     amount: 22,    status: "pending" },
  { id: 15, customer: "Cleo",    amount: 65.25, status: "paid" },
  { id: 16, customer: "Dmitri",  amount: 140,   status: "cancelled" },
  { id: 17, customer: "Ana",     amount: 55,    status: "paid" },
  { id: 18, customer: "Bo",      amount: 145.5, status: "paid" },
  { id: 19, customer: "Eve",     amount: 410,   status: "paid" },
  { id: 20, customer: "Dmitri",  amount: 777,   status: "paid" },
  { id: 21, customer: "Cleo",    amount: 12,    status: "pending" },
  { id: 22, customer: "Ana",     amount: 260,   status: "paid" },
  { id: 23, customer: "Bo",      amount: 33.75, status: "cancelled" },
  { id: 24, customer: "Eve",     amount: 150,   status: "paid" },
];

const BROKEN = new Set([7, 13, 20]);

let inFlight = 0;
let maxInFlight = 0;
let calls = 0;

const delay = (ms) => new Promise((r) => setTimeout(r, ms));

async function fetchOrderIds() {
  await delay(20);
  return ORDERS.map((o) => o.id);
}

async function fetchOrder(id) {
  calls++;
  inFlight++;
  if (inFlight > maxInFlight) maxInFlight = inFlight;
  try {
    await delay(40);
    if (BROKEN.has(id)) throw new Error(`upstream 500 for order ${id}`);
    const found = ORDERS.find((o) => o.id === id);
    if (!found) throw new Error(`no such order ${id}`);
    return { ...found };
  } finally {
    inFlight--;
  }
}

const stats = () => ({ maxInFlight, calls });
const resetStats = () => { maxInFlight = 0; calls = 0; };

module.exports = { fetchOrderIds, fetchOrder, stats, resetStats };
