// check.js - GIVEN. Do not edit this file. Run it: node check.js
const assert = require("node:assert");
const api = require("./api.js");

const EXPECTED = {
  totalRevenue: 2267.25,
  byStatus: { paid: 13, pending: 4, cancelled: 4 },
  topCustomers: [
    { name: "Eve", spent: 560 },
    { name: "Ana", spent: 550.75 },
    { name: "Bo", spent: 385.75 },
  ],
  failed: [7, 13, 20],
};

const show = (v) => JSON.stringify(v, null, 2);

(async () => {
  let report;
  const { buildReport } = require("./report.js");

  if (typeof buildReport !== "function") {
    console.log("  ERR  report.js does not export a function buildReport");
    process.exit(1);
  }

  api.resetStats();
  const t0 = Date.now();
  try {
    report = await buildReport();
  } catch (err) {
    console.log(`  ERR  buildReport threw: ${err.name}: ${err.message}`);
    console.log("       The API fails on some orders. That must not kill the whole report.");
    process.exit(1);
  }
  const elapsed = Date.now() - t0;
  const { maxInFlight, calls } = api.stats();

  let ok = 0, failed = 0;
  const check = (name, fn) => {
    try { fn(); ok++; console.log(`  OK   ${name}`); }
    catch (e) { failed++; console.log(`  FAIL ${name}\n       ${e.message.split("\n").slice(0, 12).join("\n       ")}`); }
  };

  console.log("\n--- shape -----------------------------------------------");
  check("totalRevenue", () => assert.deepStrictEqual(report?.totalRevenue, EXPECTED.totalRevenue));
  check("byStatus", () => assert.deepStrictEqual(report?.byStatus, EXPECTED.byStatus));
  check("topCustomers", () => assert.deepStrictEqual(report?.topCustomers, EXPECTED.topCustomers));
  check("failed", () => assert.deepStrictEqual(report?.failed, EXPECTED.failed));

  console.log("\n--- how it ran ------------------------------------------");
  check(`every order asked for exactly once (calls=${calls})`, () =>
    assert.strictEqual(calls, 24));
  check(`concurrency never above 5 (max seen: ${maxInFlight})`, () =>
    assert.ok(maxInFlight <= 5, `saw ${maxInFlight} in flight at once. Promise.all over all 24 is not allowed here.`));
  check(`actually parallel, not one by one (max seen: ${maxInFlight})`, () =>
    assert.ok(maxInFlight >= 2, `max in flight was ${maxInFlight}. You are awaiting one at a time.`));
  check(`finished under 500 ms (took ${elapsed} ms)`, () =>
    assert.ok(elapsed < 500, `took ${elapsed} ms. Sequential over 24 orders is ~1000 ms.`));

  console.log(`\n  ${ok} ok, ${failed} failed`);
  if (failed) {
    console.log("\n  your report:");
    console.log(show(report));
  } else {
    console.log("\n  GREEN. Stop the timer and write down the number.");
  }
  process.exit(failed ? 1 : 0);
})();
